---
development:
  cloud_name: hpij7gzzi
  api_key: '597388482293165'
  api_secret: ldMI-Vev3VdViQUFOuX02EdckHU
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hpij7gzzi
  api_key: '597388482293165'
  api_secret: ldMI-Vev3VdViQUFOuX02EdckHU
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hpij7gzzi
  api_key: '597388482293165'
  api_secret: ldMI-Vev3VdViQUFOuX02EdckHU
  enhance_image_tag: true
  static_image_support: false
